### PR TITLE
Fix incorrect shortcut for Toggle Breakpoint.

### PR DESCRIPTION
**Pull request by mlvandijk**
Fix incorrect shortcut for Toggle Breakpoint.

Included some additional small fixes:
* Fix spelling of "Javadoc".
* Fix name of reader mode feature to Rendered View. 
* Grammar here and there (add/remove commas, add hyphen)

### CODE REVIEW

**Comment by JosePaumard** [comment]
Thank you Marit, I just pushed the update on the site.

**Comment by danthe1st** [comment]
@JosePaumard Wouldn't it make sense to also merge it if the change is pushed to the site to make sure this repository is consistent? After all, if someone wants to fix something in this article in the future, it would be easier if they have the up-to-date version.

**Review by ammbra — APPROVED** [review]
Looks good to me. Thank you, Marit.

**Review by JosePaumard — APPROVED** [review]

**Comment by ammbra** [comment]
@danthe1st The changes reported on this repo are also merged. This has been done with past PRs as well. 😄

**Pull request merged**
